name: Build wheel for ARM

on:
  push:
    branches:
    tags:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3.3.1
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build TA-Lib wheels
      run: |
        docker buildx build -f Dockerfile.armhf \
          --platform linux/arm/v7 \
          --build-arg RUN_TESTS=0 \
          --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
          --load \
          -t talib:wheel .

    - name: Extract Wheels from image
      run: |
        docker run --rm -v $(pwd)/assets:/assets \
          --platform linux/arm/v7 \
          talib:wheel \
          cp -r /opt/ta-lib-python/wheels/ /assets/

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ta-lib_arm64_wheel
        path: ./assets/wheels/TA*
